import React, { useState, useEffect } from "react";
import { Typography, Grid, Card, CardContent, Button } from "@mui/material";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import { useParams, useNavigate } from "react-router-dom";
import { newsContent } from "./assets/data";

// News component
export default function NewsContent() {
  const navigate = useNavigate();
  const params = useParams();
  const [news, setNews] = useState({});

  useEffect(() => {
    let found = false;
    newsContent.forEach((content) => {
      if (Number(params.id) === content.id) {
        setNews(content);
        found = true;
        return;
      }
    });
    if (Boolean(!found)) {
      navigate("/news");
    }
  }, []);

  const goBack = () => {
    navigate("/news");
  };

  return (
    <>
      <Button startIcon={<ArrowBackIcon />} onClick={goBack}>
        Back
      </Button>

      <Grid container spacing={2} justifyContent="center">
        <Grid item key={news.id}>
          <Card>
            <CardContent>
              <Typography>{news.content}</Typography>
            </CardContent>
          </Card>
        </Grid>
      </Grid>
      <Grid container justifyContent="center">
        <Typography variant="overline" align="center" sx={{ py: 2 }}>
          Generated by ChatGPT ;)
        </Typography>
      </Grid>
    </>
  );
}
