import React from "react";
import { Typography, Grid, Card, CardContent } from "@mui/material";
import { useNavigate } from "react-router-dom";
import { newsContent } from "./assets/data";

// News component
export default function News() {
  const navigate = useNavigate();

  const viewNews = (id) => {
    navigate(`/news/${id}`);
  };

  return (
    <>
      <Grid container spacing={2} justifyContent="center">
        <Grid item xs={12}>
          <Typography variant="h4" align="center" sx={{ pt: 3 }}>
            News
          </Typography>
        </Grid>
      </Grid>
      <Grid container spacing={2} justifyContent="center">
        {newsContent.map((content) => {
          return (
            <Grid item key={content.id}>
              <Card
                sx={{ "&:hover": { boxShadow: 5 }, cursor: "pointer" }}
                onClick={() => viewNews(content.id)}
              >
                <CardContent>
                  <Typography>{content.content}</Typography>
                </CardContent>
              </Card>
            </Grid>
          );
        })}
      </Grid>
      <Grid container justifyContent="center">
        <Typography variant="overline" align="center" sx={{ py: 2 }}>
          Text Generated by ChatGPT ;)
        </Typography>
      </Grid>
    </>
  );
}
